CREATE TABLE potionorder (
 id serial PRIMARY KEY,
 firstName VARCHAR(100) NOT NULL,
 lastName VARCHAR(100) NOT NULL,
 email text UNIQUE NOT NULL,
 street1 VARCHAR(100) NOT NULL,
 street2 VARCHAR(100),
 city VARCHAR(100) NOT NULL,
 state VARCHAR(100) NOT NULL,
 zip VARCHAR(100) NOT NULL,
 phone VARCHAR(100) NOT NULL,
quantity VARCHAR(100) NOT NULL,
total VARCHAR(100) NOT NULL,
ccNum VARCHAR(100) NOT NULL,
expiration VARCHAR(100) NOT NULL,
fulfilled BOOLEAN NOT NULL,
 orderDate TIMESTAMP NOT NULL
);